# Generated by Django 4.2.4 on 2023-08-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contraseña', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('foto_perfil', models.TextField()),
                ('id_foto', models.CharField(blank=True, max_length=100, null=True)),
                ('key_validate', models.CharField(blank=True, max_length=100, null=True)),
                ('tipografia', models.CharField(max_length=100)),
                ('tamano_fuente', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ZonaUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CortAR.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('foto', models.TextField()),
                ('idFoto', models.TextField()),
                ('zona', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('like', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CortAR.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('foto', models.TextField()),
                ('idFoto', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('like', models.IntegerField()),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortAR.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortAR.usuario')),
            ],
        ),
    ]
