# Generated by Django 4.2.4 on 2023-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CortAR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tamano_fuente',
            field=models.FloatField(default=12.0),
        ),
    ]
