# Generated by Django 4.2.4 on 2023-08-19 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CortAR', '0002_alter_usuario_tamano_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
