# Generated by Django 4.2.4 on 2023-08-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CortAR', '0003_alter_comentario_fecha_alter_comentario_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='idUsuario',
            new_name='idPublicacion',
        ),
    ]
