# Generated by Django 4.2.4 on 2023-08-20 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CortAR', '0004_rename_idusuario_publicacion_idpublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
