# Generated by Django 4.2.4 on 2023-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CortAR', '0005_usuario_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='idFoto',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='idFoto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_foto',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.TextField(default=''),
        ),
    ]
