# Generated by Django 4.2.4 on 2023-08-23 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CortAR', '0006_remove_comentario_idfoto_remove_publicacion_idfoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='like',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='like',
        ),
        migrations.CreateModel(
            name='LikePublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortAR.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortAR.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LikeComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortAR.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortAR.usuario')),
            ],
        ),
    ]
