# Generated by Django 4.2.4 on 2023-08-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CortAR', '0007_remove_comentario_like_remove_publicacion_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='sugerencia',
            field=models.TextField(default=''),
        ),
    ]
